https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import unicodedata
import re
import random

# Preparing data

In [2]:
SOS_token = 0
EOS_token = 1

class Lang:
    def __init__(self, name):
        self.name = name
        self.word2index = {}
        self.word2count = {}
        self.index2word = {SOS_token: 'SOS', EOS_token: 'EOS'}
        self.n_words = 2    # for SOS and EOS tokens
        
    def add_sentence(self, sentence):
        for word in sentence.split(' '):
            self.add_word(word)
            
    def add_word(self, word):
        if word not in self.word2index:
            self.word2index[word] = self.n_words
            self.word2count[word] = 1
            self.index2word[self.n_words] = word
            self.n_words += 1
        else:
            self.word2count[word] += 1

In [3]:
def unicode_to_ascii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
    )

# Lowercase, trim, and remove non-letter characters
def normalize_string(s):
    s = unicode_to_ascii(s.lower().strip())
    s = re.sub(r"([.!?])", r" \1", s)
    s = re.sub(r"[^a-zA-Z!?]+", r" ", s)
    return s.strip()

In [4]:
def read_langs(lang1: str, lang2: str, reverse=False):
    lines = open("data/%s-%s.txt" % (lang1, lang2), encoding="utf-8").readlines()
    pairs = [[normalize_string(s) for s in l.split('\t')] for l in lines]
    
    if reverse:
        pairs = [list(reversed(p)) for p in pairs]
        input_lang = Lang(lang2)
        output_lang = Lang(lang1)
    else:
        input_lang = Lang(lang1)
        output_lang = Lang(lang2)
        
    return input_lang, output_lang, pairs

In [5]:
input_lang, output_lang, pairs = read_langs('eng', 'fra')
for pair in pairs:
    input_lang.add_sentence(pair[0])
    output_lang.add_sentence(pair[1])

In [6]:
MAX_LENGTH = 100

# Neural network module

In [7]:
class Encoder(nn.Module):
    def __init__(self, input_size, hidden_size, dropout_p=0.1):
        super(Encoder, self).__init__()
        self.hidden_size = hidden_size
        self.embedding = nn.Embedding(input_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size, batch_first=True)
        self.dropout = nn.Dropout(dropout_p)
        
    def forward(self, x):
        embedded = self.dropout(self.embedding(x))
        output, hidden = self.gru(embedded)
        return output, hidden

In [8]:
class Decoder(nn.Module):
    def __init__(self, hidden_size, output_size):
        super(Decoder, self).__init__()
        self.embedding = nn.Embedding(output_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size, batch_first=True)
        self.out = nn.Linear(hidden_size, output_size)
        
    def forward(self, encoder_outputs, encoder_hidden, target_tensor=None):
        batch_size = encoder_outputs.size(0)
        decoder_input = torch.empty(batch_size, 1, dtype=torch.long, device=encoder_outputs.device).fill(SOS_token)
        decoder_hidden = encoder_hidden
        decoder_outputs = []
        
        for i in range(MAX_LENGTH):
            decoder_output, decoder_hidden = self.forward_step(decoder_input, decoder_hidden)
            decoder_outputs.append(decoder_output)
            
            if target_tensor is not None:
                decoder_input = target_tensor[:, i].unsqueeze(1)
            else:
                _, topi = decoder_output.topk(1)
                decoder_input = topi.squeeze(-1).detach()
                
        decoder_outputs = torch.cat(decoder_outputs, dim=1)
        decoder_outputs = F.log_softmax(self.out(decoder_outputs), dim=-1)
        
        return decoder_outputs, decoder_hidden, None
    
    def forward_step(self, input, hidden):
        output = self.embedding(input)
        output = F.relu(output)
        output, hidden = self.gru(output, hidden)
        output = self.out(output)
        
        return output, hidden

# Training and evaluation of this initial encoder-decoder

In [12]:
def indexes_from_sentence(lang, sentence):
    return [lang.word2index[word] for word in sentence.split(' ')]

def tensor_from_sentence(lang, sentence):
    indexes = indexes_from_sentence(lang, sentence)
    indexes.append(EOS_token)
    return torch.tensor(indexes, dtype=torch.long).view(-1, 1)

def tensors_from_pair(pair):
    input_tensor = tensor_from_sentence(input_lang, pair[0])
    target_tensor = tensor_from_sentence(output_lang, pair[1])
    return input_tensor, target_tensor

In [9]:
encoder = Encoder(MAX_LENGTH, 20)
decoder = Decoder(20, MAX_LENGTH)

In [20]:
criterion = nn.NLLLoss()

learning_rate = 0.01
encoder_optimizer = torch.optim.SGD(encoder.parameters(), lr=learning_rate)
decoder_optimizer = torch.optim.SGD(decoder.parameters(), lr=learning_rate)

for i in range(0, 1000):
    training_examples = random.choices(pairs, k=5000)
    
    for p in training_examples:
        i, t = tensors_from_pair(p)
        
        encoder_optimizer.zero_grad()
        decoder_optimizer.zero_grad()
    
        encoded = encoder(i)
        decoded = decoder(encoded)
        
        loss = criterion(decoded, t)
        loss.backward()
        
        encoder_optimizer.step()
        decoder_optimizer.step()
    

IndexError: index out of range in self

In [18]:
[tensors_from_pair(p)[0] for p in training_examples]

[tensor([[ 180],
         [  80],
         [2385],
         [  27],
         [ 770],
         [1495],
         [  11],
         [ 222],
         [  23],
         [   1]]),
 tensor([[187],
         [188],
         [ 86],
         [ 27],
         [199],
         [444],
         [  1]]),
 tensor([[  59],
         [ 826],
         [2422],
         [ 199],
         [1994],
         [   1]]),
 tensor([[  19],
         [  27],
         [1090],
         [ 199],
         [ 358],
         [   1]]),
 tensor([[  22],
         [4027],
         [  52],
         [ 112],
         [1558],
         [ 702],
         [  80],
         [ 107],
         [   1]]),
 tensor([[4315],
         [3643],
         [1037],
         [7218],
         [   1]]),
 tensor([[  22],
         [  65],
         [ 183],
         [  42],
         [2864],
         [3063],
         [1870],
         [   1]]),
 tensor([[ 170],
         [ 332],
         [  80],
         [ 228],
         [ 171],
         [2518],
         [  23],
       